flowchart TD;
  subgraph "リスナー"
    listener
    browser
    pecareco
  end

  subgraph "配信者"
    broadcaster
  end

  style pat fill:#0000
  subgraph pat["p@YP"]
    subgraph "p-at.net (Vercel)"
      isr["Vercel CDN"]
      www["next.js"]
    end

    subgraph GCP
      direction TB
      subgraph GCE
        subgraph docker1["Docker"]
          nginxroot["Nginx(https://root.p-at.net)"]
          nginxinsecure["Nginx(http://insecure.p-at.net)"]
        end
        subgraph docker2["Docker"]
          root["rootモードPeerCast(pcp://root.p-at.net)"];
        end
      end
      dns["Cloud DNS"]
      logger["Cloud Logger"]
    end
  end

  listener["リスナーのPeerCast"]--pcp-->broadcaster
  broadcaster["配信者のPeerCast"]--pcp-->root
  browser["PCYP"]--https-->isr
  pecareco["PCYP (PeCaRecorder等のhttps未対応のソフト)"]--http-->nginxinsecure
  nginxinsecure--https-->isr
  isr--http-->www;
  www--https-->logger
  www--https-->nginxroot;
  nginxroot--http-->root;
